// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jmizxgtqvwwneuwqxbki.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImptaXp4Z3Rxdnd3bmV1d3F4YmtpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxNDU4NzYsImV4cCI6MjA1OTcyMTg3Nn0.mdqteWo3w4dp4y_JdWlU8vyiOIiH1U8oinMILflzuHg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);